# Generated by Django 6.0.7 on 2026-07-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=5)),
                ('escudo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField()),
                ('gols_mandante', models.PositiveIntegerField(blank=True, null=True)),
                ('gols_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('AO_VIVO', 'Ao Vivo'), ('FINALIZADO', 'Finalizado')], default='AGENDADO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_mandante', to='bolao.time')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='bolao.time')),
            ],
        ),
        migrations.CreateModel(
            name='Palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_mandante', models.PositiveIntegerField()),
                ('gols_visitante', models.PositiveIntegerField()),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='bolao.jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to='bolao.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'jogo'), name='palpite_unico_usuario_jogo')],
            },
        ),
    ]
