# Generated by Django 6.0.7 on 2026-07-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos/'),
        ),
    ]
