# Generated by Django 6.0.7 on 2026-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_alter_time_escudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='escudo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
